
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: snowflake_customer_purchases
      description: "some description"
      columns:
          - name: c_custkey
            tests:
              - unique
              - not_null

    - name: cumulative_query
      description: "some description"
      columns:
          - name: o_orderdate
            tests:
              - unique
              - not_null
    - name: dates
    - name: time_difference
